    
    print(files)
    capture_image()
    p1=multiprocessing.Process(target=find_images, args=(0,int(len(files)/2),files,knownFace,1))
    p2=multiprocessing.Process(target=find_images, args=(int(len(files)/2),len(files),files,knownFace,2))
    p1.start()
    p2.start()
    p1.join()
    p2.join()
    shutil.rmtree('faces', ignore_errors=True)
    shutil.rmtree('known', ignore_errors=True)
    end=time.time()
    print(end-start)